# Generated by Django 2.2.2 on 2019-09-04 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50, null=True)),
                ('add_date', models.CharField(default='2019/09/05', max_length=20, null=True)),
                ('size', models.IntegerField(choices=[(23, 'F'), (25, '25 XS'), (26, '26 S'), (27, '27 M'), (28, '28 L'), (39, '39 XL'), (30, '30 2XL'), (31, '31 3XL'), (32, '32 4XL'), (33, '5XL'), (34, '6XL')])),
                ('price', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=1000)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('clerk_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('type_of', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_count', models.IntegerField()),
                ('sell_price', models.IntegerField(default=-9999)),
                ('sale_date', models.CharField(default='2019/09/05', max_length=20, null=True)),
                ('clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Clerk')),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.All_Product')),
            ],
        ),
        migrations.AddField(
            model_name='all_product',
            name='type_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.TypeOf'),
        ),
    ]
