# Generated by Django 2.2.5 on 2019-12-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50, null=True)),
                ('add_date', models.DateField(default='2019-12-31', null=True)),
                ('price', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=1000)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('clerk_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('type_of', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TodayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_count', models.IntegerField()),
                ('base_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=1000)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Clerk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.All_Product')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_count', models.IntegerField()),
                ('sell_price', models.IntegerField(default=-9999)),
                ('sale_date', models.DateField(default='2019-12-31', null=True)),
                ('remark', models.CharField(blank=True, max_length=1000)),
                ('clerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Clerk')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.All_Product')),
            ],
        ),
        migrations.AddField(
            model_name='all_product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Size'),
        ),
        migrations.AddField(
            model_name='all_product',
            name='type_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.TypeOf'),
        ),
    ]
