# Generated by Django 2.2.2 on 2019-09-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20190905_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_product',
            name='add_date',
            field=models.CharField(default='2019/09/08', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales_record',
            name='sale_date',
            field=models.CharField(default='2019/09/08', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='TodayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_count', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Clerk')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.All_Product')),
            ],
        ),
    ]
