# Generated by Django 2.2.2 on 2019-09-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20190908_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayrecord',
            name='clerk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.Clerk'),
        ),
        migrations.AlterField(
            model_name='todayrecord',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Customer'),
        ),
    ]
