# Generated by Django 2.2.2 on 2019-09-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20190908_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.Customer'),
        ),
    ]
