# Generated by Django 2.2.2 on 2019-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20190908_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayrecord',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
