# Generated by Django 2.2.5 on 2019-09-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20190908_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_product',
            name='add_date',
            field=models.CharField(default='2019/09/11', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sales_record',
            name='sale_date',
            field=models.CharField(default='2019/09/11', max_length=20, null=True),
        ),
    ]
