# Generated by Django 2.2.5 on 2019-09-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20190911_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_record',
            name='remark',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='todayrecord',
            name='remark',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='all_product',
            name='add_date',
            field=models.DateField(default='2019-09-25', null=True),
        ),
        migrations.AlterField(
            model_name='sales_record',
            name='sale_date',
            field=models.DateField(default='2019-09-25', null=True),
        ),
    ]
